env_config:
  game_name: connect_four
  max_game_rounds: null

num_episodes: 1
seed: 42
use_ray: false
mode: random_vs_random

agents:
  player_0:
    type: random
  player_1:
    type: random

llm_backend:
  max_tokens: 250
  temperature: 0.1
  default_model: litellm_gpt-4o-mini

log_level: INFO
tensorboard_logging: false
